apiVersion: v1
kind: Service
metadata:
  name: pod-watcher
  namespace: pod-watcher
  labels:
    app: pod-watcher
spec:
  type: ClusterIP
  selector:
    app: pod-watcher
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
